ANXIETY_MODEL_ID: "halilibr/dilbazlar-bert-uncased-anxiety-disorders-recognition-balanced-tr-model-acc-92.7"
DEPRESSION_MODEL_ID: "halilibr/dilbazlar-depression-disorders-recognition-tr-model-acc-82"
DISORDER_MODEL_ID: "ensarcitak/dilbazlar-multilabel-depression-anxiety-detection-model-acc-91"
ANX_DEP_MODEL_ID: "halilibr/dilbazlar-binary-disorder-detection-model-acc-96"
